#ifndef SECRETS_EXAMPLE_H
#define SECRETS_EXAMPLE_H

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define LOCATION_LAT 42.4242
#define LOCATION_LON 42.4242

#endif  // SECRETS_EXAMPLE_H
